VERSION: 2

MODEL:
  META_ARCHITECTURE: "DinoMask2Former"
  BACKBONE:
    NAME: "build_dinov2_fpn_backbone"
  MASK_ON: true
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  DINO:
    MODEL_NAME: "dinov2_vitb14"
    PATCH_SIZE: 14
    EMBED_DIM: 768
    OUT_CHANNELS: 256
    FINETUNE_LAST_BLOCKS: 0
    WEIGHTS: ""
  MASK_FORMER:
    NUM_CLASSES: 1
    HIDDEN_DIM: 256
    MASK_DIM: 256
    DIM_FEEDFORWARD: 2048
    NHEADS: 8
    DROPOUT: 0.1
    DEC_LAYERS: 6
    NUM_OBJECT_QUERIES: 150
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 7.0
    DICE_WEIGHT: 7.0
    MASK_THRESHOLD: 0.5
    SCORE_THRESHOLD: 0.35
    TOPK_PER_IMAGE: 150
INPUT:
  FORMAT: "RGB"
  FULL_PAGE: false
  CROP_SIZE: [768, 768]
  TILE_OVERLAP: 128
  MIN_SIZE_TRAIN: [1024]
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 4096
  RANDOM_FLIP: "horizontal"
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  IMS_PER_BATCH: 1
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001
  BACKBONE_MULTIPLIER: 0.0
  MAX_ITER: 1000
  STEPS: [200, 260]
  GAMMA: 0.1
  CHECKPOINT_PERIOD: 100
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  AMP:
    ENABLED: true
TEST:
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 150
OUTPUT_DIR: "./mask2former/output"