from detectron2.config import CfgNode as CN


def add_dino_mask2former_config(cfg):
    cfg.INPUT.FORMAT = "RGB"
    cfg.INPUT.FULL_PAGE = False
    cfg.INPUT.CROP_SIZE = (768, 768)
    cfg.INPUT.TILE_OVERLAP = 128
    cfg.INPUT.MIN_SIZE_TRAIN = (1024,)
    cfg.INPUT.MIN_SIZE_TEST = 1024
    cfg.INPUT.MAX_SIZE_TRAIN = 4096
    cfg.INPUT.MAX_SIZE_TEST = 4096
    cfg.INPUT.RANDOM_FLIP = "horizontal"

    cfg.MODEL.META_ARCHITECTURE = "DinoMask2Former"
    cfg.MODEL.MASK_ON = True
    cfg.MODEL.PIXEL_MEAN = [123.675, 116.28, 103.53]
    cfg.MODEL.PIXEL_STD = [58.395, 57.12, 57.375]

    cfg.MODEL.DINO = CN()
    cfg.MODEL.DINO.MODEL_NAME = "dinov2_vitb14"
    cfg.MODEL.DINO.PATCH_SIZE = 14
    cfg.MODEL.DINO.EMBED_DIM = 768
    cfg.MODEL.DINO.OUT_CHANNELS = 256
    cfg.MODEL.DINO.FINETUNE_LAST_BLOCKS = 0
    cfg.MODEL.DINO.WEIGHTS = ""

    cfg.MODEL.MASK_FORMER = CN()
    cfg.MODEL.MASK_FORMER.NUM_CLASSES = 1
    cfg.MODEL.MASK_FORMER.HIDDEN_DIM = 256
    cfg.MODEL.MASK_FORMER.MASK_DIM = 256
    cfg.MODEL.MASK_FORMER.DIM_FEEDFORWARD = 2048
    cfg.MODEL.MASK_FORMER.NHEADS = 8
    cfg.MODEL.MASK_FORMER.DROPOUT = 0.1
    cfg.MODEL.MASK_FORMER.DEC_LAYERS = 6
    cfg.MODEL.MASK_FORMER.NUM_OBJECT_QUERIES = 150
    cfg.MODEL.MASK_FORMER.NO_OBJECT_WEIGHT = 0.1
    cfg.MODEL.MASK_FORMER.CLASS_WEIGHT = 2.0
    cfg.MODEL.MASK_FORMER.MASK_WEIGHT = 7.0
    cfg.MODEL.MASK_FORMER.DICE_WEIGHT = 7.0
    cfg.MODEL.MASK_FORMER.MASK_THRESHOLD = 0.5
    cfg.MODEL.MASK_FORMER.SCORE_THRESHOLD = 0.35
    cfg.MODEL.MASK_FORMER.TOPK_PER_IMAGE = 150

    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 0.0
    cfg.SOLVER.WEIGHT_DECAY = 0.05
    cfg.SOLVER.WEIGHT_DECAY_NORM = 0.0

    cfg.TEST.DETECTIONS_PER_IMAGE = 150


def apply_mask2former_mode(cfg):
    if not cfg.INPUT.FULL_PAGE:
        return cfg

    cfg.INPUT.CROP_SIZE = ()
    cfg.INPUT.TILE_OVERLAP = 0
    cfg.MODEL.DINO.FINETUNE_LAST_BLOCKS = 4
    cfg.SOLVER.BACKBONE_MULTIPLIER = 0.1
    return cfg